CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" (DT_MEDICAO VARCHAR(16), HR_MEDICAO VARCHAR(4), TEM_MIN REAL, CD_ESTACAO_MIN VARCHAR(4), TEM_MAX REAL, CD_ESTACAO_MAX VARCHAR(4), PREC REAL, TEMP REAL, VENTO REAL);

CREATE OR REPLACE PUMP "REFERENCE_STREAM_PUMP" AS INSERT INTO "DESTINATION_SQL_STREAM"
SELECT DT_MEDICAO, c.HR_MEDICAO, TEM_MIN, CD_ESTACAO_MIN, TEM_MAX, CD_ESTACAO_MAX, PREC, TEMP, VENTO FROM 
    (SELECT  DT_MEDICAO, a.HR_MEDICAO, b.TEM_MIN, a.CD_ESTACAO CD_ESTACAO_MIN,  b.PREC, b.TEMP, b.VENTO
        FROM "SOURCE_SQL_STREAM_001" a
        RIGHT JOIN (
            SELECT STREAM HR_MEDICAO, MIN(TEM_MIN) TEM_MIN, AVG(PREC) PREC, AVG(VENTO) VENTO, AVG(TEM_INS) TEMP
                FROM "SOURCE_SQL_STREAM_001"
                GROUP BY HR_MEDICAO,
                STEP("SOURCE_SQL_STREAM_001".ROWTIME BY INTERVAL '1' MINUTE)
        ) b ON a.TEM_MIN = b.TEM_MIN
    ) c 
    JOIN
    (SELECT  d.HR_MEDICAO, e.TEM_MAX, d.CD_ESTACAO CD_ESTACAO_MAX
        FROM "SOURCE_SQL_STREAM_001" d
        RIGHT JOIN (
            SELECT STREAM HR_MEDICAO, MAX(TEM_MAX) TEM_MAX
            FROM "SOURCE_SQL_STREAM_001"
            GROUP BY HR_MEDICAO,
            STEP("SOURCE_SQL_STREAM_001".ROWTIME BY INTERVAL '1' MINUTE)
        ) e ON d.TEM_MAX = e.TEM_MAX) f 
    ON c.HR_MEDICAO = f.HR_MEDICAO;
